import { createFileRoute, Link } from "@tanstack/react-router";
import { useEffect, useMemo, useState, type FormEvent } from "react";
import type { Session } from "@supabase/supabase-js";
import { Boxes, CheckCircle2, ChevronLeft, ExternalLink, Image as ImageIcon, LayoutDashboard, Loader2, LogOut, Menu, PackagePlus, Pencil, Plus, Search, Trash2, Upload, X } from "lucide-react";
import { supabase } from "@/lib/supabase";
import { Skeleton } from "@/components/ui/skeleton";

type Product = { id: string; name: string; category: string; description: string; specifications: string; highlights: string; image_url: string | null; published: boolean; sort_order: number };
const empty = { name: "", category: "Musculação", description: "", specifications: "", highlights: "", image_url: "", published: true, sort_order: 0 };
export const Route = createFileRoute("/admin")({ component: Admin });

function Admin() {
  const [session, setSession] = useState<Session | null>(null), [ready, setReady] = useState(false);
  const [email, setEmail] = useState(""), [password, setPassword] = useState("");
  const [products, setProducts] = useState<Product[]>([]), [form, setForm] = useState(empty);
  const [editing, setEditing] = useState<string | null>(null), [busy, setBusy] = useState(false);
  const [message, setMessage] = useState(""), [search, setSearch] = useState(""), [menu, setMenu] = useState(false);

  useEffect(() => { supabase?.auth.getSession().then(({data}) => { setSession(data.session); setReady(true) }); const l=supabase?.auth.onAuthStateChange((_e,s)=>setSession(s)); return()=>l?.data.subscription.unsubscribe() },[]);
  useEffect(() => { if(session) void loadProducts() },[session]);
  const filtered=useMemo(()=>products.filter(p=>`${p.name} ${p.category}`.toLowerCase().includes(search.toLowerCase())),[products,search]);
  const categories=new Set(products.map(p=>p.category)).size;

  async function loadProducts(){const{data,error}=await supabase!.from("products").select("*").order("sort_order").order("name");error?setMessage(error.message):setProducts(data??[])}
  async function login(e:FormEvent){e.preventDefault();setBusy(true);setMessage("");const{error}=await supabase!.auth.signInWithPassword({email,password});if(error)setMessage("E-mail ou senha inválidos.");setBusy(false)}
  async function save(e:FormEvent){e.preventDefault();setBusy(true);setMessage("");const payload={...form,image_url:form.image_url||null};const r=editing?await supabase!.from("products").update(payload).eq("id",editing):await supabase!.from("products").insert(payload);if(r.error)setMessage(r.error.message);else{setForm(empty);setEditing(null);setMessage(editing?"Alterações salvas.":"Produto cadastrado.");await loadProducts()}setBusy(false)}
  async function upload(file:File){setBusy(true);const path=`${crypto.randomUUID()}-${file.name.replace(/[^a-zA-Z0-9.-]/g,"-")}`;const{error}=await supabase!.storage.from("product-images").upload(path,file);if(error)setMessage(error.message);else setForm(v=>({...v,image_url:supabase!.storage.from("product-images").getPublicUrl(path).data.publicUrl}));setBusy(false)}
  async function remove(id:string){if(!confirm("Excluir este produto do catálogo?"))return;const{error}=await supabase!.from("products").delete().eq("id",id);error?setMessage(error.message):await loadProducts()}
  function edit(p:Product){setEditing(p.id);setForm({...p,image_url:p.image_url??""});scrollTo({top:0,behavior:"smooth"})}

  if(!ready)return <AdminSkeleton/>;
  if(!session)return <Login email={email} password={password} busy={busy} message={message} setEmail={setEmail} setPassword={setPassword} login={login}/>;

  const sidebar=<aside className="flex h-full w-72 flex-col border-r border-border bg-card/95 p-5 backdrop-blur-xl">
    <div className="mb-10 flex items-center justify-between"><Link to="/" className="flex items-center gap-3"><span className="grid size-11 place-items-center rounded-xl bg-gradient-primary shadow-glow"><Boxes className="size-5 text-primary-foreground"/></span><span><b className="block font-display text-lg leading-none">Sardinha</b><small className="text-[10px] font-bold uppercase tracking-[.24em] text-primary">Central fitness</small></span></Link><button className="lg:hidden" onClick={()=>setMenu(false)} aria-label="Fechar menu"><X/></button></div>
    <nav className="space-y-2"><SideItem icon={LayoutDashboard} label="Visão geral"/><SideItem icon={Boxes} label="Produtos" active/><button onClick={()=>{setEditing(null);setForm(empty);setMenu(false);scrollTo({top:0,behavior:"smooth"})}} className="flex w-full items-center gap-3 rounded-xl px-4 py-3 text-sm font-semibold text-muted-foreground transition hover:bg-muted hover:text-foreground"><PackagePlus size={18}/>Novo produto</button></nav>
    <div className="mt-auto rounded-2xl border border-primary/20 bg-primary/5 p-4"><p className="text-xs font-bold uppercase tracking-widest text-primary">Catálogo online</p><p className="mt-2 text-sm text-muted-foreground">Produtos publicados aparecem automaticamente no site.</p><Link to="/" className="mt-4 flex items-center gap-2 text-sm font-bold text-foreground">Abrir site <ExternalLink size={14}/></Link></div>
  </aside>;

  return <div className="min-h-screen bg-background text-foreground">
    <div className="fixed inset-y-0 left-0 z-40 hidden lg:block">{sidebar}</div>{menu&&<div className="fixed inset-0 z-50 lg:hidden"><button aria-label="Fechar menu" onClick={()=>setMenu(false)} className="absolute inset-0 bg-black/70"/><div className="relative h-full">{sidebar}</div></div>}
    <div className="lg:pl-72"><header className="sticky top-0 z-30 flex h-20 items-center gap-4 border-b border-border bg-background/85 px-4 backdrop-blur-xl md:px-8"><button onClick={()=>setMenu(true)} className="rounded-xl border border-border p-2 lg:hidden" aria-label="Abrir menu"><Menu/></button><div className="relative max-w-md flex-1"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar no catálogo" className="w-full rounded-xl border border-border bg-card py-2.5 pl-10 pr-4 text-sm outline-none focus:border-primary focus:ring-2 focus:ring-primary/15"/></div><div className="ml-auto hidden text-right sm:block"><p className="max-w-52 truncate text-sm font-semibold">{session.user.email}</p><p className="text-xs text-muted-foreground">Administrador</p></div><button onClick={()=>supabase!.auth.signOut()} className="rounded-xl border border-border p-2.5 transition hover:border-primary hover:text-primary" aria-label="Sair"><LogOut size={18}/></button></header>
      <main className="mx-auto max-w-7xl p-4 md:p-8"><section className="relative mb-8 overflow-hidden rounded-3xl border border-border bg-card p-6 md:p-8"><div className="absolute -right-16 -top-28 h-72 w-36 rotate-35 bg-gradient-primary opacity-80"/><p className="text-xs font-bold uppercase tracking-[.22em] text-primary">Gestão do catálogo</p><h1 className="mt-2 max-w-2xl font-display text-3xl font-bold md:text-4xl">Equipamentos organizados. <span className="text-gradient-primary">Vendas em movimento.</span></h1><p className="mt-3 max-w-xl text-sm text-muted-foreground">Cadastre, revise e publique os produtos apresentados aos seus clientes.</p></section>
        <div className="mb-8 grid gap-3 sm:grid-cols-3"><Stat label="Produtos" value={products.length} icon={Boxes}/><Stat label="Publicados" value={products.filter(p=>p.published).length} icon={CheckCircle2}/><Stat label="Categorias" value={categories} icon={LayoutDashboard}/></div>
        <section className="grid items-start gap-6 xl:grid-cols-[minmax(0,1.25fr)_minmax(340px,.75fr)]"><div className="order-2 xl:order-1"><div className="mb-4 flex items-end justify-between"><div><p className="text-xs font-bold uppercase tracking-widest text-primary">Inventário</p><h2 className="font-display text-2xl font-bold">Produtos cadastrados</h2></div><span className="text-xs text-muted-foreground">{filtered.length} item(ns)</span></div><div className="space-y-3">{filtered.length?filtered.map(p=><ProductRow key={p.id} product={p} edit={()=>edit(p)} remove={()=>remove(p.id)}/>):<div className="rounded-2xl border border-dashed border-border p-10 text-center"><Boxes className="mx-auto mb-3 text-muted-foreground"/><p className="font-semibold">Nenhum produto encontrado</p><p className="text-sm text-muted-foreground">Altere a busca ou cadastre um novo item.</p></div>}</div></div>
          <form onSubmit={save} className="order-1 rounded-3xl border border-border bg-card p-5 shadow-elegant xl:sticky xl:top-26 xl:order-2"><div className="mb-5 flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-widest text-primary">{editing?"Edição":"Novo item"}</p><h2 className="font-display text-xl font-bold">{editing?"Editar produto":"Cadastrar produto"}</h2></div>{editing&&<button type="button" onClick={()=>{setEditing(null);setForm(empty)}} className="rounded-lg p-2 text-muted-foreground hover:bg-muted" aria-label="Cancelar edição"><X size={18}/></button>}</div><div className="space-y-3"><Field label="Nome"><Input placeholder="Ex.: Cadeira extensora" value={form.name} onChange={name=>setForm({...form,name})}/></Field><Field label="Categoria"><Input placeholder="Ex.: Musculação" value={form.category} onChange={category=>setForm({...form,category})}/></Field><Field label="Descrição"><Area placeholder="Apresente o produto" value={form.description} onChange={description=>setForm({...form,description})}/></Field><Field label="Especificações"><Area placeholder="Altura, largura, peso..." value={form.specifications} onChange={specifications=>setForm({...form,specifications})}/></Field><Field label="Destaques"><Area placeholder="Um benefício por linha" value={form.highlights} onChange={highlights=>setForm({...form,highlights})}/></Field><label className="group flex cursor-pointer items-center gap-3 rounded-2xl border border-dashed border-border p-4 transition hover:border-primary hover:bg-primary/5"><span className="grid size-10 place-items-center rounded-xl bg-muted group-hover:bg-primary group-hover:text-primary-foreground"><Upload size={18}/></span><span><b className="block text-sm">Imagem do produto</b><small className="text-muted-foreground">PNG, JPG ou WebP</small></span><input type="file" accept="image/*" className="hidden" onChange={e=>e.target.files?.[0]&&upload(e.target.files[0])}/></label>{form.image_url&&<img src={form.image_url} alt="Prévia do produto" className="h-40 w-full rounded-2xl bg-background object-contain p-2"/>}<label className="flex items-center justify-between rounded-xl bg-muted px-4 py-3 text-sm font-semibold">Publicar no catálogo<input type="checkbox" checked={form.published} onChange={e=>setForm({...form,published:e.target.checked})} className="size-4 accent-orange-500"/></label>{message&&<p className="rounded-xl bg-muted p-3 text-sm">{message}</p>}<button disabled={busy} className="flex w-full items-center justify-center gap-2 rounded-full bg-gradient-primary px-6 py-3 font-bold text-primary-foreground shadow-glow transition hover:scale-[1.01] disabled:opacity-60">{busy?<Loader2 className="animate-spin" size={18}/>:<Plus size={18}/>} {editing?"Salvar alterações":"Cadastrar produto"}</button></div></form>
        </section></main></div></div>;
}

function Login(p:{email:string;password:string;busy:boolean;message:string;setEmail:(v:string)=>void;setPassword:(v:string)=>void;login:(e:FormEvent)=>void}){return <Center><div className="absolute inset-y-0 left-0 w-2 bg-gradient-primary"/><form onSubmit={p.login} className="w-full max-w-md rounded-3xl border border-border bg-card p-8 shadow-elegant"><span className="mb-8 grid size-12 place-items-center rounded-xl bg-gradient-primary shadow-glow"><Boxes/></span><p className="text-xs font-bold uppercase tracking-[.22em] text-primary">Acesso restrito</p><h1 className="mt-2 font-display text-3xl font-bold">Central do catálogo</h1><p className="mt-2 mb-7 text-sm text-muted-foreground">Entre para gerenciar os equipamentos exibidos no site.</p><div className="space-y-4"><Field label="E-mail"><Input type="email" placeholder="seu@email.com" value={p.email} onChange={p.setEmail}/></Field><Field label="Senha"><Input type="password" placeholder="Sua senha" value={p.password} onChange={p.setPassword}/></Field>{p.message&&<p className="text-sm text-destructive">{p.message}</p>}<button disabled={p.busy} className="w-full rounded-full bg-gradient-primary py-3 font-bold text-primary-foreground shadow-glow">{p.busy?"Entrando...":"Entrar no painel"}</button><Link to="/" className="flex items-center justify-center gap-2 text-sm text-muted-foreground hover:text-primary"><ChevronLeft size={15}/>Voltar ao site</Link></div></form></Center>}
function AdminSkeleton(){return <div className="min-h-screen bg-background text-foreground" role="status" aria-label="Carregando painel administrativo"><aside className="fixed inset-y-0 left-0 hidden w-72 border-r border-border bg-card p-5 lg:block"><div className="flex items-center gap-3"><Skeleton className="size-11"/><div className="space-y-2"><Skeleton className="h-4 w-28"/><Skeleton className="h-2 w-20"/></div></div><div className="mt-12 space-y-3"><Skeleton className="h-12 w-full"/><Skeleton className="h-12 w-4/5"/><Skeleton className="h-12 w-11/12"/></div><Skeleton className="absolute bottom-5 left-5 right-5 h-32 rounded-2xl"/></aside><div className="lg:pl-72"><header className="flex h-20 items-center border-b border-border px-4 md:px-8"><Skeleton className="h-10 max-w-md flex-1"/><Skeleton className="ml-auto size-10"/></header><main className="mx-auto max-w-7xl p-4 md:p-8"><Skeleton className="h-48 w-full rounded-3xl"/><div className="my-8 grid gap-3 sm:grid-cols-3">{[0,1,2].map(i=><Skeleton key={i} className="h-20 rounded-2xl"/>)}</div><div className="grid gap-6 xl:grid-cols-[1.25fr_.75fr]"><div className="space-y-3"><Skeleton className="mb-6 h-8 w-56"/>{[0,1,2,3].map(i=><div key={i} className="flex gap-4 rounded-2xl border border-border bg-card p-3"><Skeleton className="h-18 w-22"/><div className="flex-1 space-y-3 py-1"><Skeleton className="h-4 w-2/3"/><Skeleton className="h-3 w-1/3"/><Skeleton className="h-5 w-20 rounded-full"/></div></div>)}</div><div className="rounded-3xl border border-border bg-card p-5"><Skeleton className="h-6 w-44"/><div className="mt-6 space-y-4"><Skeleton className="h-12"/><Skeleton className="h-12"/><Skeleton className="h-24"/><Skeleton className="h-24"/><Skeleton className="h-14"/></div></div></div></main></div><span className="sr-only">Carregando...</span></div>}
function SideItem({icon:Icon,label,active=false}:{icon:typeof Boxes;label:string;active?:boolean}){return <div className={`flex items-center gap-3 rounded-xl px-4 py-3 text-sm font-semibold ${active?"bg-primary text-primary-foreground shadow-glow":"text-muted-foreground"}`}><Icon size={18}/>{label}</div>}
function Stat({label,value,icon:Icon}:{label:string;value:number;icon:typeof Boxes}){return <div className="flex items-center gap-4 rounded-2xl border border-border bg-card p-4"><span className="grid size-11 place-items-center rounded-xl bg-primary/10 text-primary"><Icon size={20}/></span><div><b className="font-display text-2xl">{value}</b><p className="text-xs text-muted-foreground">{label}</p></div></div>}
function ProductRow({product:p,edit,remove}:{product:Product;edit:()=>void;remove:()=>void}){return <article className="group flex items-center gap-4 rounded-2xl border border-border bg-card p-3 transition hover:border-primary/50"><div className="grid h-18 w-22 shrink-0 place-items-center overflow-hidden rounded-xl bg-muted">{p.image_url?<img src={p.image_url} alt="" className="size-full object-contain"/>:<ImageIcon className="text-muted-foreground"/>}</div><div className="min-w-0 flex-1"><h3 className="truncate font-display font-bold">{p.name}</h3><p className="truncate text-sm text-muted-foreground">{p.category}</p><span className={`mt-2 inline-block rounded-full px-2 py-0.5 text-[10px] font-bold uppercase ${p.published?"bg-primary/10 text-primary":"bg-muted text-muted-foreground"}`}>{p.published?"Publicado":"Rascunho"}</span></div><button onClick={edit} aria-label="Editar" className="rounded-xl p-2 text-muted-foreground hover:bg-muted hover:text-primary"><Pencil size={17}/></button><button onClick={remove} aria-label="Excluir" className="rounded-xl p-2 text-muted-foreground hover:bg-destructive/10 hover:text-destructive"><Trash2 size={17}/></button></article>}
function Center({children}:{children:React.ReactNode}){return <main className="relative grid min-h-screen place-items-center overflow-hidden bg-background p-4 text-foreground">{children}</main>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="block"><span className="mb-1.5 block text-xs font-bold uppercase tracking-wider text-muted-foreground">{label}</span>{children}</label>}
function Input({value,onChange,...props}:{value:string;onChange:(v:string)=>void;type?:string;placeholder:string}){return <input {...props} required value={value} onChange={e=>onChange(e.target.value)} className="w-full rounded-xl border border-border bg-background px-4 py-3 text-sm outline-none transition focus:border-primary focus:ring-2 focus:ring-primary/15"/>}
function Area({value,onChange,placeholder}:{value:string;onChange:(v:string)=>void;placeholder:string}){return <textarea placeholder={placeholder} value={value} onChange={e=>onChange(e.target.value)} rows={3} className="w-full resize-y rounded-xl border border-border bg-background px-4 py-3 text-sm outline-none transition focus:border-primary focus:ring-2 focus:ring-primary/15"/>}
